### ISSUE TITLE
the export ignores Layouts files and exports only Templates

### ISSUE THREAD

**Issue by erredeco** [CPS-IT/TYPO3-mask_export#19]
I created a Mask element that uses both Templates/ and Layouts/ ; 
The Templates/test.html file is something like that:

```
<f:layout name="Default" />
<f:section name="content">
....
</f:section>
```

Layouts/Default.html is:
```
<f:render section="content" />
```

When exporting the element, I see that just the file

EXT:mytestext/Resources/Private/Templates/TtContent/test.html is created, obviously without the 
`<f:section name="content">` part.

TypoScript:
```
tt_content.mytestext_test= FLUIDTEMPLATE
tt_content.mytestext_test {
    file = EXT:mytestext/Resources/Private/Templates/TtContent/test.html
....
```

**Comment by IchHabRecht** [comment]
Hi Riccardo,

I had a look and mask doesn't generate Layout templates on its own. As it is necessary to adjust the template files to be compatible with the export, the extension has to create own template files and cannot reuse existing ones. So if you modified the mask templates after generation, you have to modify the templates in the export as well.

**Comment by IchHabRecht** [comment]
Hi Riccardo,

Can we close this issue or is there anything I can do?

**Comment by erredeco** [comment]
Hi Nicole. Your answer confirms  what I was afraid of. Even if not using Layouts, if you modify the template, the export exports the "standard" one generated by Mask and you have to modify it by yourself.
If there is no solution, you can close it. Thank you

**Comment by IchHabRecht** [comment]
The exports needs its own templates due to the dataProcessor handling. Those aren't the default ones mask is using (because mask uses an own Controller which preprocesses content elements on its own, but the extension uses plain TypoScript). The recommended way to use the export is to use it before any template is adjusted. So you "only" need to modify the templates generated by the export. I really hope this can solve your problem in any way.
